pid_gains:
  arm_joint_1:
    p: 100.0
    i: 0.01
    d: 10.0
  arm_joint_2:
    p: 100.0
    i: 0.01
    d: 10.0
  arm_joint_3:
    p: 100.0
    i: 0.01
    d: 10.0
  arm_joint_4:
    p: 100.0
    i: 0.01
    d: 10.0
  arm_joint_5:
    p: 100.0
    i: 0.01
    d: 10.0
  arm_joint_6:
    p: 100.0
    i: 0.01
    d: 10.0
  arm_joint_7:
    p: 100.0
    i: 0.01
    d: 10.0
