# Publish all joint states -----------------------------------
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

positions_effort_controller:
  type: effort_controllers/JointGroupPositionController
  joints: ["arm_joint_1",
           "arm_joint_2",
           "arm_joint_3",
           "arm_joint_4",
           "arm_joint_5",
           "arm_joint_6",
           "arm_joint_7"]
  arm_joint_1:
    pid: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
  arm_joint_2:
    pid: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
  arm_joint_3:
    pid: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }
  arm_joint_4:
    pid: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }
  arm_joint_5:
    pid: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }
  arm_joint_6:
    pid: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
  arm_joint_7:
    pid: { p: 2000, d: 20, i: 0.0, i_clamp: 1 }

task_space_kinova_robot:
  type: "kinova_controllers/KinovaTaskSpaceControllerRobot"
  controlled_frame: "arm_end_effector"
  target_pose_topic: "/target_pose"
  current_pose_topic: "/current_pose"
  publish_ros: true
  publish_ros_rate: 10

task_space_kinova_sim:
  type: "kinova_controllers/KinovaTaskSpaceControllerSim"
  controlled_frame: "arm_end_effector"
  target_pose_topic: "/target_pose"
  current_pose_topic: "/current_pose"
  publish_ros: true
  publish_ros_rate: 10

ik_kinova_robot:
  description_name: "/kinova_no_gripper"
  type: "kinova_controllers/IKControllerKinova"
  target_pose_topic: "/target_pose"
  current_pose_topic: "/current_pose"
  publish_ros: true
  debug: true
  max_velocity: 0.3
  max_acceleration: 100.0
  joint_names:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
    - arm_joint_6
    - arm_joint_7
  p_gains: [100.0, 100.0, 100.0, 100.0, 500.0, 500.0, 500.0]
  d_gains: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
  default_configuration: [0.0, 0.26, 3.14, -2.27, 0.0, 0.96, 1.57]
  lower_limits: [-6.28, -2.41, -6.28, -2.66, -6.28, -2.23, -6.28]
  upper_limits: [6.28, 2.41, 6.28, 2.66, 6.28, 2.23, 6.28]
  root_link: arm_base_link
  end_effector_link: arm_end_effector_link


ik_kinova_sim:
  description_name: "/kinova_no_gripper"
  type: "robot_control_ros/IKControllerEffortSim"
  target_pose_topic: "/target_pose"
  current_pose_topic: "/current_pose"
  publish_ros: true
  debug: false
  joint_names:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
    - arm_joint_6
    - arm_joint_7
  max_velocity: 0.3
  max_acceleration: 100.0
  p_gains: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
  d_gains: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
  default_configuration: [0.0, 0.26, 3.14, -2.27, 0.0, 0.96, 1.57]
  lower_limits: [-6.28, -2.41, -6.28, -2.66, -6.28, -2.23, -6.28]
  upper_limits: [6.28, 2.41, 6.28, 2.66, 6.28, 2.23, 6.28]
  root_link: arm_base_link
  end_effector_link: arm_end_effector_link