# Publish all joint states -----------------------------------
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

gripper_position_controller:
  type: "position_controllers/JointPositionController"
  joint: "gripper"

joint_velocity_controller:
  type: "kinova_controllers/KinovaJointVelocityController"
  joint_names:
    - $(arg prefix)joint_1
    - $(arg prefix)joint_2
    - $(arg prefix)joint_3
    - $(arg prefix)joint_4
    - $(arg prefix)joint_5
    - $(arg prefix)joint_6
    - $(arg prefix)joint_7
