joint_zeros:
  $(arg prefix)joint_1: 0.0
  $(arg prefix)joint_2: 0.0
  $(arg prefix)joint_3: 0.0
  $(arg prefix)joint_4: 0.0
  $(arg prefix)joint_5: 0.0
  $(arg prefix)joint_6: 0.0
  $(arg prefix)joint_7: 0.0
